# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=name,resolution@refreshrate,position,scale

monitor=DP-1,3440x1440@179.98,0x0,1
monitor=eDP-1,2560x1440@120,3440x0,1.6

# Workspace assignments
workspace=1,monitor:DP-1
workspace=2,monitor:DP-1
workspace=3,monitor:DP-1
workspace=4,monitor:DP-1
workspace=5,monitor:DP-1
workspace=6,monitor:DP-1
workspace=7,monitor:DP-1
workspace=8,monitor:eDP-1
workspace=9,monitor:eDP-1
